name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - uses: actions/setup-node@master
    - name: Install Dependencies
      run: composer update --ignore-platform-reqs
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run build
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{secrets.SERVER}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        server-dir: ${{secrets.SERVER_DIR}}
        protocol: ftp
